### ISSUE TITLE
Double free or corruption (fasttop) crash

### ISSUE THREAD

**Issue by iatsiuk** [coturn/coturn#257]
Steps to reproduce bug:
1. start turnserver:

```sh
# turnserver -n --cert=./server_cert.pem --pkey=./server_key_no_pw.pem -V
```

2. execute turnutils_uclient:

```sh
# turnutils_uclient -S -k ./client_key_no_pw.pem 127.0.0.1
```

3. turn server almost instantly crashes.

[core dump.gz](https://github.com/coturn/coturn/files/2211285/core.gz)
[turn_10723_2018-07-19.log.gz](https://github.com/coturn/coturn/files/2211286/turn_10723_2018-07-19.log.gz)

**Comment by misi** [comment]
Many Thanks I could reproduce it. 

However this is a very edge case. 
I have to work on many more urgent cases. 
It would be great if you could please help and debug it further and send a PR with the fix if possible.

```
Thread 8 "turnserver" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe7fff700 (LWP 8868)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: Nincs ilyen fájl vagy könyvtár.
(gdb) bt                                                                                                                          
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff54a1801 in __GI_abort () at abort.c:79
#2  0x00007ffff54ea897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff5617b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff54f190a in malloc_printerr (str=str@entry=0x7ffff5619828 "double free or corruption (fasttop)") at malloc.c:5350
#4  0x00007ffff54f9004 in _int_free (have_lock=0, p=0x7fffc8016da0, av=0x7fffc8000020) at malloc.c:4230
#5  __GI___libc_free (mem=0x7fffc8016db0) at malloc.c:3124
#6  0x00007ffff759b1a9 in EVP_PKEY_free () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#7  0x00007ffff72259ed in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#8  0x00007ffff721955d in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#9  0x00007ffff71fd4d7 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#10 0x00007ffff72059aa in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#11 0x00007ffff720f7d5 in SSL_read () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#12 0x0000555555561c82 in ssl_read (fd=204, ssl=0x7fffc8015bc0, nbh=0x7fffc8005bb0, verbose=2) at src/apps/relay/ns_ioalib_engine_impl.c:1837
#13 0x0000555555588ef3 in handle_udp_packet (server=0x7fffec34ce58, sm=0x7fffec34d2b8, ioa_eng=0x7fffec3371f8, ts=0x7fffec337050) at src/apps/relay/dtls_listener.c:351
#14 0x000055555558a2e8 in udp_server_input_handler (fd=204, what=2, arg=0x7fffec34ce58) at src/apps/relay/dtls_listener.c:728
#15 0x00007ffff6fc8ed8 in ?? () from /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.6
#16 0x00007ffff6fc991f in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.6
#17 0x0000555555573f6f in run_events (eb=0x7fffc8000b60, e=0x7fffec3371f8) at src/apps/relay/netengine.c:1579
#18 0x00005555555744a3 in run_general_relay_thread (arg=0x7fffec337010) at src/apps/relay/netengine.c:1697
#19 0x00007ffff58596db in start_thread (arg=0x7fffe7fff700) at pthread_create.c:463
#20 0x00007ffff558288f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by misi** [comment]
If you add the --CA-file= option then it should work!
In my understanding CA is mandatory, so we need to add a check to avoid such situation..

**Comment by misi** [comment]
Sorry. I was wrong you are right it should work without CA, according the code..

**Comment by misi** [comment]
back trace with ssl debug symbols
```
bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff54a1801 in __GI_abort () at abort.c:79
#2  0x00007ffff54ea897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff5617b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff54f190a in malloc_printerr (str=str@entry=0x7ffff5619828 "double free or corruption (fasttop)") at malloc.c:5350
#4  0x00007ffff54f9004 in _int_free (have_lock=0, p=0x7fffe0017110, av=0x7fffe0000020) at malloc.c:4230
#5  __GI___libc_free (mem=0x7fffe0017120) at malloc.c:3124
#6  0x00007ffff759b1a9 in EVP_PKEY_free (x=x@entry=0x7fffe002d730) at ../crypto/evp/p_lib.c:421
#7  0x00007ffff72259ed in tls_process_cke_ecdhe (al=<optimized out>, pkt=<optimized out>, s=<optimized out>) at ../ssl/statem/statem_srvr.c:2386
#8  tls_process_client_key_exchange (s=0x7fffe00154f0, pkt=<optimized out>) at ../ssl/statem/statem_srvr.c:2571
#9  0x00007ffff721955d in read_state_machine (s=0x7fffe00154f0) at ../ssl/statem/statem.c:591
#10 state_machine (s=0x7fffe00154f0, server=1) at ../ssl/statem/statem.c:387
#11 0x00007ffff71fd4d7 in dtls1_read_bytes (s=0x7fffe00154f0, type=23, recvd_type=0x0, buf=0x7fffe000946c "", len=16384, peek=0) at ../ssl/record/rec_layer_d1.c:375
#12 0x00007ffff72059aa in ssl3_read_internal (s=0x7fffe00154f0, buf=0x7fffe000946c, len=16384, peek=0) at ../ssl/s3_lib.c:3840
#13 0x00007ffff720f7d5 in SSL_read (s=<optimized out>, buf=<optimized out>, num=<optimized out>) at ../ssl/ssl_lib.c:1651
#14 0x0000555555561c82 in ssl_read (fd=170, ssl=0x7fffe00154f0, nbh=0x7fffe0005460, verbose=2) at src/apps/relay/ns_ioalib_engine_impl.c:1837
#15 0x0000555555588ef3 in handle_udp_packet (server=0x7fffe7355e58, sm=0x7fffe73562b8, ioa_eng=0x7fffe73401f8, ts=0x7fffe7340050) at src/apps/relay/dtls_listener.c:351
#16 0x000055555558a2e8 in udp_server_input_handler (fd=170, what=2, arg=0x7fffe7355e58) at src/apps/relay/dtls_listener.c:728
#17 0x00007ffff6fc8ed8 in ?? () from /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.6
#18 0x00007ffff6fc991f in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.6
#19 0x0000555555573f6f in run_events (eb=0x7fffe0000b60, e=0x7fffe73401f8) at src/apps/relay/netengine.c:1579
#20 0x00005555555744a3 in run_general_relay_thread (arg=0x7fffe7340010) at src/apps/relay/netengine.c:1697
#21 0x00007ffff58596db in start_thread (arg=0x7fffef540700) at pthread_create.c:463
#22 0x00007ffff558288f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by iatsiuk** [comment]
> It would be great if you could please help and debug it further and send a PR with the fix if possible.

I'd like to help you but unfortunately it is not possible: javascript is the only language i know. Sorry for that.

> If you add the --CA-file= option then it should work!

Self signed certificates don't require CA as far as i know. Does Coturn server support self signed certificates? Besides i have tested this command with certificates from Let's Encrypt and '--CA-file' option and the problem is still there.

Please let me know if i can help you somehow with testing or debugging this issue.

**Comment by misi** [comment]
I think I found it. Could you please check the latest git master branch?

**Comment by misi** [comment]
I think it is fixed. Please open a new issue if you still experience this error.
